### ISSUE TITLE
Pkgconfig causes building problems

### ISSUE THREAD

**Issue by HeavyTony2** [sebastinas/python-libdiscid#15]
I've been working on adding the package to conda-forge.  Even installing the package through the standard pip command was often difficult. A typical error message was about "Python.h" missing. However, I realized there was no problem if pkgconfig wasn't installed.
https://github.com/conda-forge/staged-recipes/pull/24262

**Comment by sebastinas** [comment]
Since it's building a C extension, the development files of the Python installation are required. If `Python.h` cannot be found, there is something wrong with the Python environment.

**Comment by HeavyTony2** [comment]
And the problem is likely to be pkgconfig

**Comment by sebastinas** [comment]
pkgconfig checks for system libraries which in this case is libdiscid. Whether or not conan properly supports pkgconfig is one question, that you need a working Python installation is another. In this case: the Python development headers and a working C compiler are required.
