### ISSUE TITLE
the windows eggs?

### ISSUE THREAD

**Issue by NathanTech7713** [sebastinas/python-libdiscid#7]
Hi there,
I'm trying to install this library on windows 10 and it says there are eggs available into which I must simply drop discid.dll, but I can not seem to find the eggs mentioned?
I've tried pip install python-libdiscid from a direction where I have discid.dll but with no success, it errors out wanting discid/discid.h. I ran the same command from my libdiscid download in the include directory with similar results.

Any help would be appreciated.

**Comment by sebastinas** [comment]
Indeed, eggs are missing since version 0.4.1. I'll try to set something up so that the next release includes eggs again.

**Comment by NathanTech7713** [comment]
I'd definitely appreciate that!
Do you have any advice in the mean time on a way to compile it for windows, and/or is a release forthcoming soon? Don't mean to be a bother, I just have a project that's waiting on a module like this :)

**Comment by sebastinas** [comment]
32 bit eggs are available from https://github.com/sebastinas/python-libdiscid/actions/runs/524265940 (check the artifacts).

**Comment by NathanTech7713** [comment]
THANK YOU VERY MUCH! Extremely excited to get cracking with this module.
