### ISSUE TITLE
Minimum supported Python version 3.6!?

### ISSUE THREAD

**Issue by phw** [sebastinas/python-libdiscid#8]
Just noticed this in the Picard CI: python-libdiscid makes use of Python f strings in https://github.com/sebastinas/python-libdiscid/blob/master/libdiscid/__init__.py#L41

This needs at least Python 3.6. As we still also test with Python 3.5 in the Picard CI this threw a syntax error.

Intentional or not? I don't have an issue with having Python 3.6 set as minimum version for python-libdiscid. If that's intentional we'll just skip the CI run with python-libdiscid + Python 3.5 in Picard. And eventually we will use 3.6 as minimum anyway.

But I'd say document 3.6 as minimum version in the README.

**Comment by sebastinas** [comment]
Yes, that was intentional after Python 3.5 reached its end of life. I wonder why python_requires in setup.cfg seems to be ignored, though.

**Comment by sebastinas** [comment]
Oh, there was a typo.

**Comment by sebastinas** [comment]
I've released a fixed version to PyPI and yanked the 2.0 release. pip under Python 3.5 should install version 1.1 again. Sorry for the inconvenience.

**Comment by phw** [comment]
Thanks a lot, that simplified things again. I'll check if this works for our CI as expected
